=== anouillz/HEI_SEM4/BeyondRDB/Class4/cars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cars">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="car" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="brand" type="xs:string" />
                            <xs:element name="model" type="xs:string" />
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1886"/>
                                        <xs:maxInclusive value="2025"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="engine">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="door_number">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="2"/>
                                        <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="weight">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="1000.0"/>
                                        <xs:maxInclusive value="3500.0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="currency" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== anouillz/HEI_SEM4/BeyondRDB/Class4/cars_w_erros.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cars.xsd">
    <car id="1">
        <brand>Toyota</brand>
        <model>Corolla</model>
        <year>2020</year>
        <engine type="petrol">1.8L</engine>
        <door_number>3</door_number>
        <price currency="CHF">20000</price>
    </car>
    <car id="2">
        <brand>Ford</brand>
        <model>Mustang</model>
        <year>2023</year>
        <engine type="petrol">5.0L</engine>
        <door_number>10</door_number>
        <weight>2000</weight>
        <price currency="USD">55000</price>
    </car>
    <car id="3">
        <brand>Honda</brand>
        <model>Civic</model>
        <year>2040</year>
        <engine type="diesel">2.0L</engine>
        <door_number>5</door_number>
        <weight>2000</weight>
        <price currency="USD">18000</price>
    </car>
    <car id="4">
        <brand>BMW</brand>
        <model>X5</model>
        <year>2021</year>
        <engine type="petrol">3.0L</engine>
        <door_number>5</door_number>
        <weight>2000</weight>
        <price currency="CHF">60000</price>
    </car>
    <car id="5">
        <brand>Tesla</brand>
        <model>Model 3</model>
        <year>2022</year>
        <engine type="electric">2.0L</engine>
        <door_number>5</door_number>
        <weight>2000</weight>
        <price currency="USD">LoliloL</price>
    </car>
</cars>
